// flow-typed signature: 937bee0e6764460da1da68d00ff43bfc
// flow-typed version: <<STUB>>/ga-browser_v^1.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ga-browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ga-browser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ga-browser/index' {
  declare module.exports: $Exports<'ga-browser'>;
}
declare module 'ga-browser/index.js' {
  declare module.exports: $Exports<'ga-browser'>;
}
