// flow-typed signature: f5320272cd4f9c9ffce2be52819cbfba
// flow-typed version: <<STUB>>/ga-lite_v^2.0.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ga-lite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ga-lite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ga-lite/dist/ga-lite' {
  declare module.exports: any;
}

declare module 'ga-lite/dist/ga-lite.min' {
  declare module.exports: any;
}

declare module 'ga-lite/src/build-event-url' {
  declare module.exports: any;
}

declare module 'ga-lite/src/commands/create' {
  declare module.exports: any;
}

declare module 'ga-lite/src/commands/get-by-name' {
  declare module.exports: any;
}

declare module 'ga-lite/src/do-not-track-enabled' {
  declare module.exports: any;
}

declare module 'ga-lite/src/fields-to-params' {
  declare module.exports: any;
}

declare module 'ga-lite/src/ga-lite-commands' {
  declare module.exports: any;
}

declare module 'ga-lite/src/ga-lite' {
  declare module.exports: any;
}

declare module 'ga-lite/src/get-base-url' {
  declare module.exports: any;
}

declare module 'ga-lite/src/get-optional-url-param' {
  declare module.exports: any;
}

declare module 'ga-lite/src/get-tasks-in-command-queue' {
  declare module.exports: any;
}

declare module 'ga-lite/src/get-user-id' {
  declare module.exports: any;
}

declare module 'ga-lite/src/object-to-query-string' {
  declare module.exports: any;
}

declare module 'ga-lite/src/require-ga-lite' {
  declare module.exports: any;
}

declare module 'ga-lite/src/send-to' {
  declare module.exports: any;
}

declare module 'ga-lite/src/simple-polyfill-array-from' {
  declare module.exports: any;
}

declare module 'ga-lite/src/tracker-store' {
  declare module.exports: any;
}

declare module 'ga-lite/src/tracker' {
  declare module.exports: any;
}

declare module 'ga-lite/test/browser-tests/specs/galite' {
  declare module.exports: any;
}

declare module 'ga-lite/test/browser-tests/wdio.conf' {
  declare module.exports: any;
}

declare module 'ga-lite/test/unit-tests/build-event-url' {
  declare module.exports: any;
}

declare module 'ga-lite/test/unit-tests/do-not-track-enabled' {
  declare module.exports: any;
}

declare module 'ga-lite/test/unit-tests/fields-to-params' {
  declare module.exports: any;
}

declare module 'ga-lite/test/unit-tests/ga-lite' {
  declare module.exports: any;
}

declare module 'ga-lite/test/unit-tests/get-optional-url-param' {
  declare module.exports: any;
}

declare module 'ga-lite/test/unit-tests/get-tasks-in-command-queue' {
  declare module.exports: any;
}

declare module 'ga-lite/test/unit-tests/get-user-id' {
  declare module.exports: any;
}

declare module 'ga-lite/test/unit-tests/mock-storage' {
  declare module.exports: any;
}

declare module 'ga-lite/test/unit-tests/object-to-query-string' {
  declare module.exports: any;
}

declare module 'ga-lite/test/unit-tests/require-ga-lite' {
  declare module.exports: any;
}

declare module 'ga-lite/test/unit-tests/send-to' {
  declare module.exports: any;
}

declare module 'ga-lite/test/unit-tests/tracker-store' {
  declare module.exports: any;
}

declare module 'ga-lite/test/unit-tests/tracker' {
  declare module.exports: any;
}

declare module 'ga-lite/test/unit-tests/utils' {
  declare module.exports: any;
}

declare module 'ga-lite/webpack.config-test.babel' {
  declare module.exports: any;
}

declare module 'ga-lite/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ga-lite/dist/ga-lite.js' {
  declare module.exports: $Exports<'ga-lite/dist/ga-lite'>;
}
declare module 'ga-lite/dist/ga-lite.min.js' {
  declare module.exports: $Exports<'ga-lite/dist/ga-lite.min'>;
}
declare module 'ga-lite/src/build-event-url.js' {
  declare module.exports: $Exports<'ga-lite/src/build-event-url'>;
}
declare module 'ga-lite/src/commands/create.js' {
  declare module.exports: $Exports<'ga-lite/src/commands/create'>;
}
declare module 'ga-lite/src/commands/get-by-name.js' {
  declare module.exports: $Exports<'ga-lite/src/commands/get-by-name'>;
}
declare module 'ga-lite/src/do-not-track-enabled.js' {
  declare module.exports: $Exports<'ga-lite/src/do-not-track-enabled'>;
}
declare module 'ga-lite/src/fields-to-params.js' {
  declare module.exports: $Exports<'ga-lite/src/fields-to-params'>;
}
declare module 'ga-lite/src/ga-lite-commands.js' {
  declare module.exports: $Exports<'ga-lite/src/ga-lite-commands'>;
}
declare module 'ga-lite/src/ga-lite.js' {
  declare module.exports: $Exports<'ga-lite/src/ga-lite'>;
}
declare module 'ga-lite/src/get-base-url.js' {
  declare module.exports: $Exports<'ga-lite/src/get-base-url'>;
}
declare module 'ga-lite/src/get-optional-url-param.js' {
  declare module.exports: $Exports<'ga-lite/src/get-optional-url-param'>;
}
declare module 'ga-lite/src/get-tasks-in-command-queue.js' {
  declare module.exports: $Exports<'ga-lite/src/get-tasks-in-command-queue'>;
}
declare module 'ga-lite/src/get-user-id.js' {
  declare module.exports: $Exports<'ga-lite/src/get-user-id'>;
}
declare module 'ga-lite/src/object-to-query-string.js' {
  declare module.exports: $Exports<'ga-lite/src/object-to-query-string'>;
}
declare module 'ga-lite/src/require-ga-lite.js' {
  declare module.exports: $Exports<'ga-lite/src/require-ga-lite'>;
}
declare module 'ga-lite/src/send-to.js' {
  declare module.exports: $Exports<'ga-lite/src/send-to'>;
}
declare module 'ga-lite/src/simple-polyfill-array-from.js' {
  declare module.exports: $Exports<'ga-lite/src/simple-polyfill-array-from'>;
}
declare module 'ga-lite/src/tracker-store.js' {
  declare module.exports: $Exports<'ga-lite/src/tracker-store'>;
}
declare module 'ga-lite/src/tracker.js' {
  declare module.exports: $Exports<'ga-lite/src/tracker'>;
}
declare module 'ga-lite/test/browser-tests/specs/galite.js' {
  declare module.exports: $Exports<'ga-lite/test/browser-tests/specs/galite'>;
}
declare module 'ga-lite/test/browser-tests/wdio.conf.js' {
  declare module.exports: $Exports<'ga-lite/test/browser-tests/wdio.conf'>;
}
declare module 'ga-lite/test/unit-tests/build-event-url.js' {
  declare module.exports: $Exports<'ga-lite/test/unit-tests/build-event-url'>;
}
declare module 'ga-lite/test/unit-tests/do-not-track-enabled.js' {
  declare module.exports: $Exports<'ga-lite/test/unit-tests/do-not-track-enabled'>;
}
declare module 'ga-lite/test/unit-tests/fields-to-params.js' {
  declare module.exports: $Exports<'ga-lite/test/unit-tests/fields-to-params'>;
}
declare module 'ga-lite/test/unit-tests/ga-lite.js' {
  declare module.exports: $Exports<'ga-lite/test/unit-tests/ga-lite'>;
}
declare module 'ga-lite/test/unit-tests/get-optional-url-param.js' {
  declare module.exports: $Exports<'ga-lite/test/unit-tests/get-optional-url-param'>;
}
declare module 'ga-lite/test/unit-tests/get-tasks-in-command-queue.js' {
  declare module.exports: $Exports<'ga-lite/test/unit-tests/get-tasks-in-command-queue'>;
}
declare module 'ga-lite/test/unit-tests/get-user-id.js' {
  declare module.exports: $Exports<'ga-lite/test/unit-tests/get-user-id'>;
}
declare module 'ga-lite/test/unit-tests/mock-storage.js' {
  declare module.exports: $Exports<'ga-lite/test/unit-tests/mock-storage'>;
}
declare module 'ga-lite/test/unit-tests/object-to-query-string.js' {
  declare module.exports: $Exports<'ga-lite/test/unit-tests/object-to-query-string'>;
}
declare module 'ga-lite/test/unit-tests/require-ga-lite.js' {
  declare module.exports: $Exports<'ga-lite/test/unit-tests/require-ga-lite'>;
}
declare module 'ga-lite/test/unit-tests/send-to.js' {
  declare module.exports: $Exports<'ga-lite/test/unit-tests/send-to'>;
}
declare module 'ga-lite/test/unit-tests/tracker-store.js' {
  declare module.exports: $Exports<'ga-lite/test/unit-tests/tracker-store'>;
}
declare module 'ga-lite/test/unit-tests/tracker.js' {
  declare module.exports: $Exports<'ga-lite/test/unit-tests/tracker'>;
}
declare module 'ga-lite/test/unit-tests/utils.js' {
  declare module.exports: $Exports<'ga-lite/test/unit-tests/utils'>;
}
declare module 'ga-lite/webpack.config-test.babel.js' {
  declare module.exports: $Exports<'ga-lite/webpack.config-test.babel'>;
}
declare module 'ga-lite/webpack.config.js' {
  declare module.exports: $Exports<'ga-lite/webpack.config'>;
}
