// flow-typed signature: 3c3761e6b82805f836e48b9d5f5a8eea
// flow-typed version: <<STUB>>/node-static_v^0.7.11/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-static'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-static' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-static/bin/cli' {
  declare module.exports: any;
}

declare module 'node-static/examples/file-server' {
  declare module.exports: any;
}

declare module 'node-static/lib/node-static' {
  declare module.exports: any;
}

declare module 'node-static/lib/node-static/util' {
  declare module.exports: any;
}

declare module 'node-static/test/integration/node-static-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-static/bin/cli.js' {
  declare module.exports: $Exports<'node-static/bin/cli'>;
}
declare module 'node-static/examples/file-server.js' {
  declare module.exports: $Exports<'node-static/examples/file-server'>;
}
declare module 'node-static/lib/node-static.js' {
  declare module.exports: $Exports<'node-static/lib/node-static'>;
}
declare module 'node-static/lib/node-static/util.js' {
  declare module.exports: $Exports<'node-static/lib/node-static/util'>;
}
declare module 'node-static/test/integration/node-static-test.js' {
  declare module.exports: $Exports<'node-static/test/integration/node-static-test'>;
}
